import type { Metadata } from "next";

import "./globals.css";
import { experimental_useFormState } from "react-dom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="p-4">{children}</body>
    </html>
  );
};

export default RootLayout;
